SELECT ANIMAL_INS.ANIMAL_ID	, ANIMAL_INS.NAME from ANIMAL_INS 
join ANIMAL_OUTS on ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
where ANIMAL_OUTS.DATETIME < ANIMAL_INS.DATETIME
order by ANIMAL_INS.DATETIME asc